# This is Created for Jenkins-SA Installed Outside the Cluster. For inside jenkins pod. we don't need Tokens as they are mounted automatically. 
# Some Prods don't recommend this approach as the Cluster token goes out. 
apiVersion: v1
kind: Config

clusters:
  - name: kubeadm-cluster
    cluster:
      server: https://10.0.10.13:6443
      certificate-authority-data: < Put YOu CA Here : Located here : /etc/kubernetes/pki/ca.crt> # for Mutual Tls, First User/Application varifies the Certificate of Api Server to avoid sharing data with Hackers
users:
  - name: jenkins-deployer
    user:
      token: < Put YOur Token Here: Command to Create token is: "kubectl create token <name of SA/User>  -n <namespace> --duration=8760h"
contexts:
  - name: jenkins-deployer@kubeadm-cluster
    context:
      cluster: kubeadm-cluster
      user: jenkins-deployer
      namespace: 11-microservices

current-context: jenkins-deployer@kubeadm-cluster

