# This is Created for Jenkins-SA Installed Outside the Cluster. For inside jenkins pod. we don't need Tokens as they are mounted automatically. 
# Some Prods don't recommend this approach as the Cluster token goes out. 
apiVersion: v1
kind: Config

clusters:
  - name: kubeadm-cluster
    cluster:
      server: https://10.0.10.13:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRm5VMUhNV01aODh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBNE1UTXhOelEwTVRkYUZ3MHpOakE0TVRBeE56UTVNVGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN1OUhzOHJDM3M0NDlSa0h0RElZWWtpWFNuQkxtc3FVOU9xazBjN2twUld5eUxtWXRkMTJPcFV1YlgKYjB0NllvOGo2N1R1dFFBN05wQ3hxakorVmRmSjliZnVmMzFneVNJS1pKTUY5R083K3VTb1BXR3NuK1hxZ05PbApWQzZwdFcyWkE2Nk5FMUY1QUJqRGNOcE9DMWpnMGUxZlNqSFliby9JdXN1Ry9teC8raTFic1g5MEw0ZmxlcCtNCkpGdDJZUlNRT3JaNTcraEhMRk8yTDNvNUpFeldZM0NvV0ZPWGJIMzFQcU5DL0VJSnpKTTZDL1FibGZodzJXT3kKcXk1aURhN2kxaFFYb21vSnZidjFXMndvemxCQVBITGxNNWhVUDFOMUxrcUFMNEEzc09wQ3hpRENLK3pJRlNKRAp1Vi9pVFAvcWVKRUcrQWswQ0RQcWZJRWFkWTM5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUUXNBZjRSb00rQ0FyQW9JbzlPV0E1ejZHdExUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXprTGdudlYwegptTXdzQnYzQ29BcmRFc1RjR0FJc2kzZ3I4bGViYW40Mi9NbDlIY2xKaEdOdm82Y1o5RkU0cTVQdGFpNk1LSzk5CkI3dmxyM21LdktWa2I1alVmYWJrWXNRdzV6emdGL2dONURac08ybUYzSG1FdDJsdVlkU2d2R3pEbVZKNnJIR3oKdThOVS80KzBjQkF4R05tMHRmeHlkeTFPQXR4bkd6NnRUY0VMUUdFcTljUGc4MXFReFlyNnBRQWdVRmQ2Q0tOcgpoeGphdEVIZU1DMGFOMHlpZDlOV1BNNDl3aU43YnduaHU3VlBKZWlzc3gwMVJ0eFpWWDNnMVBNTW1UaGRYa0d0ClAyeW1ZMGtYODh2ZVpKa3dKdFQrQUhIcFgvMDZ2cHVMc1BIK2xqaGhzZWJxUkl1RG9Xa2JYN0RwS09UeVBnTlMKR2JCWXVZN3hlQjMwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

users:
  - name: jenkins-deployer
    user:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il81bGNJUWdFZ0RkbnhJdnZ1MHpZNjNIellhaEY1eXF0RE4ybm1xN1pfUmcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxODE4Nzc2MDM3LCJpYXQiOjE3ODcyNDAwMzcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYjQzNjE2YTUtOTA3Ni00Mzk4LWE5MmYtNzUyNWJiZDljMjc2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiIxMS1taWNyb3NlcnZpY2VzIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtZGVwbG95ZXIiLCJ1aWQiOiI2MmFiOGQxMC1lYTIzLTQzOGUtYmQ5MS01MGVlZGRiZjI4MGYifX0sIm5iZiI6MTc4NzI0MDAzNywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OjExLW1pY3Jvc2VydmljZXM6amVua2lucy1kZXBsb3llciJ9.rqkhn9zzL0SrtaFm-Q0GZ_kCZ3pPZrgtPyz0rB9BlqSZcVwyN9mw_b6ow7Lwl27Bt9NqczyPx6qD0X2ZBBnaodPHrOkIg-kGVWqfFJS6MJg7A9tsLCgSVSkzb1mVtdqIKlyFPkRA-frpODClkTuHhYA4u7FA9g-QZ_fLHyCmquVrau89J2ZD_-Ei2Y76RvY98uBUx0KZ9UgmparTpVyyYWSMqIg5frw8JBtbHb5fmNzUBuYmXlzTZcu_73dx7Q381fEoKkk7nCU14KlhP_xq7Ut0pT5fI3z5_I5uMeWZuEty0nrUJ6sSDF9qOysmPUFfP_K-XRzjf-eclJ2uxf3SLw

contexts:
  - name: jenkins-deployer@kubeadm-cluster
    context:
      cluster: kubeadm-cluster
      user: jenkins-deployer
      namespace: 11-microservices

current-context: jenkins-deployer@kubeadm-cluster

